"""empty message

Revision ID: 8ee7d74a5157
Revises: 286ff26ab5ff
Create Date: 2023-07-20 16:18:22.133937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee7d74a5157'
down_revision = '286ff26ab5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition'),
    sa.UniqueConstraint('term')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms')
    # ### end Alembic commands ###
